### ISSUE TITLE
Redundant line?

### ISSUE THREAD

**Issue by wbajzek** [MeeBlip/meeblip-synth#3]
Not a big deal, but I am wondering what the purpose of this is, as I am attempting to write my own custom firmware from scratch. Isn't doing this at the beginning of the block sufficient?
https://github.com/MeeBlip/meeblip-synth/blob/master/meeblip-micro.asm#L1110

**Comment by jgrahame** [comment]
I seem to recall that this was all about ensuring that the chip got a short write pulse.
